// This file was automatically generated by AI Short Film Storyboard Suite (Client Fallback)
// Saved At: 2026-05-31T03:12:08.769Z

export const SAVED_PROJECT_DATA = {
  savedAt: "2026-05-31T03:12:08.769Z",
  currentStep: 9,
  highestStepReached: 9,
  globalBrief: {
  "title": "CHÚ CHÓ NHỎ VÀ Ổ BÁNH MÌ",
  "genre": "Animation, Drama, Family",
  "aspectRatio": "16:9",
  "visualStyle": "3D Pixar style, vibrant colors, expressive character designs",
  "language": "Vietnamese",
  "scriptText": "Nội dung\nBim là chú chó nhỏ luôn giành ăn với bạn bè. Một ngày nọ, Bim giấu hết bánh mì vào hang riêng. Nhưng trời mưa lớn khiến hang bị ngập.\nCao trào\nBim đói bụng và không còn gì để ăn.\nKết thúc\nNhững người bạn từng bị Bim ích kỷ vẫn chia sẻ thức ăn cho cậu.\nThông điệp\n“Biết sẻ chia sẽ nhận lại yêu thương.”\nLời dẫn\n“Trong khu rừng nhỏ, có một chú chó chỉ nghĩ cho riêng mình…”\nLời thoại\nBim: “Tất cả bánh mì là của mình!”\nThỏ con: “Nhưng tụi mình cũng đói mà…”\nBim (xúc động): “Mình xin lỗi…”"
},
  scenes: [
  {
    "sequenceOrder": 1,
    "description": "In a lush green forest, Bim the little dog greedily pulls a basket of bread away from his animal friends. Narrator: 'Trong khu rừng nhỏ, có một chú chó chỉ nghĩ cho riêng mình...'",
    "durationSeconds": 4,
    "transitionLogic": "Camera pans right as Bim runs away with the bread.",
    "id": "Scene_1"
  },
  {
    "sequenceOrder": 2,
    "description": "Bim runs towards his secret cave, holding the bread tightly and shouting proudly: 'Tất cả bánh mì là của mình!'",
    "durationSeconds": 3,
    "transitionLogic": "Cut to a close-up of the sad friends left behind.",
    "id": "Scene_2"
  },
  {
    "sequenceOrder": 3,
    "description": "The little rabbit looks down sadly, stomach rumbling, and says softly: 'Nhưng tụi mình cũng đói mà...'",
    "durationSeconds": 3,
    "transitionLogic": "Dissolve to Bim inside his dark, cozy cave.",
    "id": "Scene_3"
  },
  {
    "sequenceOrder": 4,
    "description": "Bim stuffs all the loaves of bread into a deep hole inside his cave, smiling selfishly.",
    "durationSeconds": 4,
    "transitionLogic": "Match cut to the dark sky outside as heavy rain clouds roll in.",
    "id": "Scene_4"
  },
  {
    "sequenceOrder": 5,
    "description": "A sudden torrential rainstorm begins, with heavy rain pouring down on the forest and lightning flashing.",
    "durationSeconds": 3,
    "transitionLogic": "Fast camera pan following the rushing water flowing into the cave entrance.",
    "id": "Scene_5"
  },
  {
    "sequenceOrder": 6,
    "description": "Water floods Bim's cave. Bim frantically tries to save his bread, but the muddy water sweeps it all away, leaving him empty-handed.",
    "durationSeconds": 5,
    "transitionLogic": "Fade out to indicate the passage of time until the next morning.",
    "id": "Scene_6"
  },
  {
    "sequenceOrder": 7,
    "description": "The rain stops. Bim sits outside his wet, ruined cave, shivering from cold and crying with an empty, rumbling stomach.",
    "durationSeconds": 4,
    "transitionLogic": "Camera pans slowly to the left as two figures approach.",
    "id": "Scene_7"
  },
  {
    "sequenceOrder": 8,
    "description": "The little rabbit and squirrel approach Bim, holding a warm, dry piece of bread together, offering it to him with kind smiles.",
    "durationSeconds": 4,
    "transitionLogic": "Close-up on Bim's tearful and surprised face.",
    "id": "Scene_8"
  },
  {
    "sequenceOrder": 9,
    "description": "Bim takes the bread, tears welling up in his eyes, and says with deep emotion: 'Mình xin lỗi...'",
    "durationSeconds": 4,
    "transitionLogic": "Zoom out to show the friends hugging warmly under the morning sun.",
    "id": "Scene_9"
  },
  {
    "sequenceOrder": 10,
    "description": "The friends happily share the bread together under a beautiful rainbow. Text onscreen: 'Biết sẻ chia sẽ nhận lại yêu thương.'",
    "durationSeconds": 5,
    "transitionLogic": "Slow fade to black.",
    "id": "Scene_10"
  }
],
  keyElements: [
  {
    "id": "Element_Character_Bim",
    "type": "character",
    "name": "Bim",
    "description": "A young, greedy little puppy who hoards food but learns a deep lesson about sharing after losing his stash.",
    "appearanceDetails": "A cute, fluffy golden-brown puppy with large, expressive dark eyes, floppy ears, a tiny black nose, and a small blue collar. Designed in a highly expressive 3D Pixar style with soft, tactile fur.",
    "imagePrompt": "Prompt of Look A: character-sheet layout: left: head-and-shoulders portrait of the character with a fluffy golden-brown puppy with large expressive dark eyes, floppy ears, and a small blue collar | right: full-body standing pose (front view, back view, and side view) with a fluffy golden-brown puppy with large expressive dark eyes, floppy ears, and a small blue collar, holding a clean wicker basket of bread in a proud, happy pose. The background is a solid neutral studio grey. High-key soft warm lighting illuminates the scene, bringing out the soft velvet-like fur textures and glossy plastic eye details with an energetic and mischievous expression. Prompt of Look B: character-sheet layout: left: head-and-shoulders portrait of the character with a wet, shivering golden-brown puppy with clumpy matted fur, drooping ears, and large teary eyes | right: full-body standing pose (front view, back view, and side view) with a wet, shivering golden-brown puppy with clumpy matted fur, drooping ears, and large teary eyes, looking down with a slouched posture, empty-handed. The background is a solid neutral studio grey. Low-key cool blue studio lighting highlights damp fur textures and wet glistening tear streaks with a deeply sorrowful and repentant expression.",
    "looks": [
      "Look A: Clean, proud, and selfishly holding the bread basket with fluffy golden-brown fur.",
      "Look B: Wet, shivering, and tearful with clumpy, matted golden-brown fur after the flood."
    ],
    "isGenerating": false,
  
  },
  {
    "id": "Element_Character_Rabbit",
    "type": "character",
    "name": "Little Rabbit",
    "description": "Bim's gentle and compassionate friend who chooses to forgive Bim and share a dry piece of bread.",
    "appearanceDetails": "A small, chubby white rabbit with floppy pink-lined ears, big round black eyes, a soft pink nose, and a tiny green knitted vest. Designed in a friendly 3D Pixar style.",
    "imagePrompt": "character-sheet layout: left: head-and-shoulders portrait of a small, chubby white rabbit with floppy pink-lined ears, big black eyes, and a tiny green knitted vest | right: full-body standing pose (front view, back view, and side view) with a small, chubby white rabbit with floppy pink-lined ears, big black eyes, and a tiny green knitted vest, holding out a warm, dry piece of golden bread. The background is a clean neutral grey studio backdrop. Soft, diffused warm studio lighting highlights the fuzzy felt-like white fur and the detailed knitted fabric textures, showcasing a gentle, compassionate, and welcoming expression.",
    "looks": [
      "Look A: Standard - Kind and soft, wearing a green knitted vest and offering bread."
    ],
    "isGenerating": false,
  
  },
  {
    "id": "Element_Location_LushForest",
    "type": "location",
    "name": "Lush Green Forest",
    "description": "The vibrant home of the animals, shifting from a sunny paradise to a dark storm, and finally to a bright morning with a rainbow.",
    "appearanceDetails": "Oversized forest vegetation, vibrant mossy trees, colorful mushrooms, and soft green grass in a stylized 3D Pixar aesthetic.",
    "imagePrompt": "A wide shot of a magical, vibrant forest clearing surrounded by giant mossy trees, oversized colorful mushrooms, and soft green grass, entirely empty of characters. The composition shows a winding dirt path fading into the distant soft-focus woods. The lighting transitions from warm morning sunlight filtering through the dense canopy to cool volumetric mist, casting a soft, whimsical glow over the scene. The color palette is rich with deep emerald greens, warm earth tones, and soft golden highlights. Texture details are sharp on the mossy tree bark and dew-covered leaves, creating a peaceful, fairytale-like atmosphere.",
    "isGenerating": false,
  
  },
  {
    "id": "Element_Location_SecretCave",
    "type": "location",
    "name": "Bim's Secret Cave",
    "description": "A hidden dome-like cave under tree roots where Bim hides his bread, which becomes dark, damp, and flooded during the storm.",
    "appearanceDetails": "A snug, dirt-walled interior sheltered by massive, gnarled tree roots, featuring a deep storage hollow in the back wall. Swamped with muddy puddle textures post-storm.",
    "imagePrompt": "A cinematic shot of a small, dome-shaped underground cave hollowed out beneath massive, gnarled tree roots, empty of characters. The camera angle looks from inside towards the narrow cave entrance, revealing a dark, rain-swept forest outside. The interior lighting is dim and atmospheric, with cold blue light from the storm exterior splashing onto the wet, muddy floor and casting deep shadows in the corners. The color scheme is dominated by cool slate greys, wet earth browns, and dark blues. High-detail textures showcase slick mud pools, dripping tree roots, and damp clay walls, conveying a cold, ruined, and isolated mood.",
    "isGenerating": false,
  
  },
  {
    "id": "Element_Prop_BreadBasket",
    "type": "prop",
    "name": "Woven Basket of Bread",
    "description": "A rustic wicker basket packed with fresh, warm loaves of bread, serving as the central object of desire and sharing.",
    "appearanceDetails": "A light brown hand-woven wicker basket with a clean white linen liner, overflowing with golden-brown baguettes and round bread loaves showing flour-dusted crusts.",
    "imagePrompt": "A close-up reference shot of a rustic hand-woven wicker basket filled with golden-brown bread loaves and baguettes, draped with a soft white linen cloth, isolated on a clean, dark wood surface. The lighting is a warm spotlight from the side, casting soft shadows and highlighting the crispy, cracked texture of the bread crusts and the detailed weave of the wicker. The composition is a tight macro shot focusing on the warm bread crumbs, creating a highly detailed, inviting, and tangible food texture in a 3D Pixar style.",
    "isGenerating": false,
  
  }
],
  storyboard: [
  {
    "id": "Shot_01",
    "sceneId": "Scene_1",
    "locationElementId": "Element_Location_LushForest",
    "characterIds": [
      "Element_Character_Bim",
      "Element_Character_Rabbit"
    ],
    "durationSeconds": 4,
    "storyBeat": "Bim in his proud, clean state greedily pulls the heavy bread basket away from his animal friends in the sunlit forest path.",
    "cinematography": {
      "scale": "medium-wide",
      "angle": "eye-level",
      "movement": "gentle track-left"
    },
    "audioLayers": {
      "bgm": "Light whimsical orchestral woodwinds",
      "narration": "Trong khu rừng nhỏ, có một chú chó chỉ nghĩ cho riêng mình...",
      "sfx": "leaves rustling softly under paws, puppy breathing excitedly"
    },
    "startFramePrompt": "Bim, a fluffy golden-brown puppy with large expressive dark eyes, floppy ears, and a small blue collar, is captured mid-stride clutching a rustic wicker basket of fresh bread with a proud, selfish grin. Beside him on the soft green grass of the lush forest, a small white rabbit with pink-lined ears in a green knitted vest watches him with a sad, drooping posture. The bright morning sun filters through giant mossy trees, illuminating the golden-brown crusts of the bread and the soft velvet texture of Bim's clean fur. The composition is a medium-wide shot emphasizing the distance growing between the puppy and his friend.",
    "videoPrompt": "The camera gently tracks left, keeping focus on Bim as he greedily hugs the bread basket tighter and turns his back on the rabbit. Bim sneers over his shoulder before dashing away off-screen to the right. The white rabbit in the background droops its ears further and sighs. SFX: <quick pattering puppy footsteps on dirt, rustling of wicker basket>.",
    "dialogue": "",
    "isGeneratingStartFrame": false,
  
  },
  {
    "id": "Shot_02",
    "sceneId": "Scene_2",
    "locationElementId": "Element_Location_LushForest",
    "characterIds": [
      "Element_Character_Bim"
    ],
    "durationSeconds": 3,
    "storyBeat": "Bim runs fast toward his secret cave holding the basket tightly, boastfully shouting that the bread belongs entirely to him.",
    "cinematography": {
      "scale": "medium",
      "angle": "low-angle",
      "movement": "slow camera-tilt"
    },
    "audioLayers": {
      "bgm": "Upbeat playful brass and woodwinds",
      "narration": "",
      "sfx": "panting puppy breaths, rapid footfalls on trail"
    },
    "startFramePrompt": "Bim, the fluffy golden-brown puppy with the blue collar, runs triumphantly along a winding dirt path that leads toward a dark, root-sheltered cave entrance. He holds the hand-woven wicker basket of warm golden bread loaves close to his chest with both paws, his face wearing a wide, boastful grin with eyes squeezed shut in self-satisfaction. A low-angle shot captures his energetic movement against the tall, sun-dappled green trees. The warm sunlight accents the crispy texture of the bread crusts.",
    "videoPrompt": "The camera tilts upward slightly as Bim runs past the lens, pointing his snout into the air. He shouts out joyfully, his jaw moving in sync with the line 'Tất cả bánh mì là của mình!'. The loaves of bread jiggle inside the wicker basket with each bouncy step he takes before he disappears into the cave entrance. SFX: <boastful puppy barks, rhythmic pattering of paws>.",
    "dialogue": "Tất cả bánh mì là của mình!",
    "isGeneratingStartFrame": false,
  
  },
  {
    "id": "Shot_03",
    "sceneId": "Scene_3",
    "locationElementId": "Element_Location_LushForest",
    "characterIds": [
      "Element_Character_Rabbit"
    ],
    "durationSeconds": 3,
    "storyBeat": "The sad little rabbit stands left behind in the forest, looking down as its stomach rumbles with hunger.",
    "cinematography": {
      "scale": "close-up",
      "angle": "high-angle",
      "movement": "slow push-in"
    },
    "audioLayers": {
      "bgm": "Melancholic solo acoustic guitar",
      "narration": "",
      "sfx": "soft stomach rumble, low wind whistling through leaves"
    },
    "startFramePrompt": "A close-up high-angle shot of the small, chubby white rabbit in a green knitted vest, standing alone in the clearing of the lush forest. His long floppy pink-lined ears droop low beside his face, and his large round black eyes glistens with unshed tears as he stares downward at his empty paws. The background shows soft-focus mossy tree trunks. The soft, diffuse forest light highlights the fluffy texture of his white fur and the fine weave of his knitted vest.",
    "videoPrompt": "The camera slowly pushes in on the rabbit's sad face. The rabbit places his right paw over his round belly as it rumbles, his tiny pink nose twitching sorrowfully. He looks up slightly, his mouth trembling as he softly whispers 'Nhưng tụi mình cũng đói mà...'. SFX: <soft gurgling stomach rumble, quiet sigh>.",
    "dialogue": "Nhưng tụi mình cũng đói mà...",
    "isGeneratingStartFrame": false,
  
  },
  {
    "id": "Shot_04",
    "sceneId": "Scene_4",
    "locationElementId": "Element_Location_SecretCave",
    "characterIds": [
      "Element_Character_Bim"
    ],
    "durationSeconds": 4,
    "storyBeat": "Inside his cozy cave, Bim stashes all the stolen bread loaves into a deep, dry hole in the mud wall.",
    "cinematography": {
      "scale": "medium-close",
      "angle": "eye-level",
      "movement": "sliding hand-drift"
    },
    "audioLayers": {
      "bgm": "Sneaky, mischievous double bass plucked notes",
      "narration": "",
      "sfx": "bread crusts scraping on dirt, puppy chuckling"
    },
    "startFramePrompt": "A medium-close eye-level shot inside Bim's secret cave, surrounded by gnarled tree roots and dark dirt walls. Bim, the fluffy golden-brown puppy with the blue collar, crouches next to a deep storage hollow in the clay wall, a greedy and highly satisfied smile on his face. He is holding a golden baguette, about to slide it into the dark hole alongside several other stashed bread loaves. Dim, warm atmospheric light illuminates the scene, catching the dust motes in the air and the rich texture of the dry soil.",
    "videoPrompt": "The camera slides slowly to the right. Bim pushes the golden baguette deep into the dark hole, then grabs two more round loaves from the wicker basket and cams them tightly inside. He pats the dirt surrounding the entrance of the hole with his front paws, giggling mischievously. SFX: <dry scraping of bread crusts, soft dirt thudding, puppy panting giggles>.",
    "dialogue": "",
    "isGeneratingStartFrame": false,
  
  },
  {
    "id": "Shot_05",
    "sceneId": "Scene_5",
    "locationElementId": "Element_Location_LushForest",
    "characterIds": [],
    "durationSeconds": 3,
    "storyBeat": "A massive rainstorm strikes the forest, bringing dark clouds, pouring rain, and brilliant flashes of lightning.",
    "cinematography": {
      "scale": "extreme-wide",
      "angle": "bird-eye",
      "movement": "slow camera-tilt"
    },
    "audioLayers": {
      "bgm": "Dramatic and heavy orchestral strings",
      "narration": "",
      "sfx": "loud sudden thunder clap, torrential pouring rain"
    },
    "startFramePrompt": "An extreme-wide bird-eye shot of the lush green forest canopy bowing under heavy storm winds. The sky is filled with dark, churning charcoal grey rain clouds. A bright, sharp flash of blue-white lightning cracks across the sky, momentarily illuminating the violent, driving sheets of rain washing over the giant, shivering trees and pooling on the forest floor below. High-contrast cool lighting dominates the scene.",
    "videoPrompt": "The camera slowly tilts downward through the heavy rain. Thick torrents of water stream off the giant leaves and splash violently into muddy puddles on the forest floor, creating miniature rushing streams. The wind whips branches back and forth across the frame. SFX: <deafening crack of thunder, roaring wind, heavy water splashing>.",
    "dialogue": "",
    "isGeneratingStartFrame": false,
  
  },
  {
    "id": "Shot_06",
    "sceneId": "Scene_6",
    "locationElementId": "Element_Location_SecretCave",
    "characterIds": [
      "Element_Character_Bim"
    ],
    "durationSeconds": 5,
    "storyBeat": "The cave floods rapidly with muddy water. Bim tries frantically to save his bread, but the torrent sweeps the loaves away, leaving him empty-handed.",
    "cinematography": {
      "scale": "medium",
      "angle": "tilted Dutch-angle",
      "movement": "slow push-in"
    },
    "audioLayers": {
      "bgm": "High-tempo chaotic orchestral percussion",
      "narration": "",
      "sfx": "rushing, splashing water, distressed puppy whimpering"
    },
    "startFramePrompt": "Inside the dimly lit, root-walled secret cave, captured in a tilted Dutch-angle medium shot. Bim, now with wet, slightly clumpy golden-brown fur and wide, panicked dark eyes, stands in rushing, ankle-deep muddy brown water. The current is violently pouring through the cave entrance directly toward the storage hole, where the bread loaves are beginning to float out. The lighting is cold, cast in deep blues and muddy brown shadows.",
    "videoPrompt": "The camera slowly pushes in as Bim splashes frantically, reaching his front paws out to grab the floating loaves of bread. A sudden surge of rushing water sweeps all the bread out of the hole and carries them out of the frame. Bim slips on the wet mud, splashing down into the puddle, and looks at his empty, wet paws in utter shock and despair. SFX: <gushing water splashes, distressed whimpers, liquid sloshing>.",
    "dialogue": "",
    "isGeneratingStartFrame": false,
  
  },
  {
    "id": "Shot_07",
    "sceneId": "Scene_7",
    "locationElementId": "Element_Location_SecretCave",
    "characterIds": [
      "Element_Character_Bim"
    ],
    "durationSeconds": 4,
    "storyBeat": "The rain stops. Bim sits outside his ruined cave, shivering from the cold, crying over his lost food on an empty stomach.",
    "cinematography": {
      "scale": "medium",
      "angle": "high-angle",
      "movement": "static block"
    },
    "audioLayers": {
      "bgm": "Somatic, low-pitched melancholic violin",
      "narration": "",
      "sfx": "water dripping from leaves, low cold wind, puppy crying"
    },
    "startFramePrompt": "A high-angle medium shot outside the mud-streaked, wet cave entrance. Bim is in his Look B state: wet, shivering, with clumpy matted golden-brown fur, drooping ears, and wet tear streaks glistening on his cheeks under a dim, overcast grey sky. He sits huddled on the damp earth, hugging his shivering body. The wet mud and dripping tree roots surround him in cool slate grey and damp brown tones.",
    "videoPrompt": "The camera remains static, capturing Bim's body trembling with cold. He buries his face in his wet paws, his small shoulders shaking as he whimpers. A prominent, hollow gurgling sound comes from his belly, causing him to squeeze his eyes shut tighter in sadness. SFX: <soft, heartbreaking whimpers, loud stomach growl, slow rhythmic water dripping>.",
    "dialogue": "",
    "isGeneratingStartFrame": false,
  
  },
  {
    "id": "Shot_08",
    "sceneId": "Scene_8",
    "locationElementId": "Element_Location_LushForest",
    "characterIds": [
      "Element_Character_Bim",
      "Element_Character_Rabbit"
    ],
    "durationSeconds": 4,
    "storyBeat": "The little rabbit and a squirrel approach the wet, crying Bim, holding a dry, warm piece of bread to share.",
    "cinematography": {
      "scale": "medium-wide",
      "angle": "eye-level",
      "movement": "slow push-in"
    },
    "audioLayers": {
      "bgm": "Warm, gentle piano and acoustic guitar transition",
      "narration": "",
      "sfx": "soft footsteps on wet grass, birds beginning to chirp"
    },
    "startFramePrompt": "A medium-wide shot of the wet, shivering Bim looking up in tearful surprise from his spot outside the cave. Walking toward him along the damp green forest path is the small white rabbit in his green knitted vest, carrying a large, warm-looking piece of golden-brown dry bread. Warm morning sunbeams begin to pierce through the wet forest canopy, casting a soft golden light over the characters and glistening on the wet grass.",
    "videoPrompt": "The camera slowly pushes in on the rabbit as he stops in front of Bim. The rabbit kneels down slightly, offering a kind, gentle smile and holding the bread piece out with both paws. The background squirrel nods encouragingly. The warm lighting intensifies, highlighting the steam rising from the fresh bread. SFX: <soft rustling grass, sweet morning bird chirps>.",
    "dialogue": "",
    "isGeneratingStartFrame": false,
  
  },
  {
    "id": "Shot_09",
    "sceneId": "Scene_9",
    "locationElementId": "Element_Location_LushForest",
    "characterIds": [
      "Element_Character_Bim",
      "Element_Character_Rabbit"
    ],
    "durationSeconds": 4,
    "storyBeat": "Bim takes the bread with trembling paws, crying tears of regret and saying sorry to his friend.",
    "cinematography": {
      "scale": "close-up",
      "angle": "eye-level",
      "movement": "slow push-in"
    },
    "audioLayers": {
      "bgm": "Emotional, swelling orchestral melody",
      "narration": "",
      "sfx": "sniffling, soft rustling of bread being accepted"
    },
    "startFramePrompt": "A close-up eye-level shot of Bim's face. He is still wet with clumpy golden-brown fur, but his large dark eyes are filled with deep emotion and glistening tears. His wet paws are gently reaching out to touch the warm, dry golden bread piece held by the white rabbit. The warm morning sunlight catches the tears rolling down his cheek. The background is a soft, warm green blur.",
    "videoPrompt": "The camera slowly pushes in closer to Bim's face as he takes the bread into his paws. Fresh tears fall from his eyes, and he sniffs deeply. He looks up directly into the rabbit's eyes, his mouth trembling as he speaks the words 'Mình xin lỗi...'. His droopy ears lift up slightly in relief. SFX: <sniffling, soft, emotional puppy voice saying 'Mình xin lỗi...'>.",
    "dialogue": "Mình xin lỗi...",
    "isGeneratingStartFrame": false,
  
  },
  {
    "id": "Shot_10",
    "sceneId": "Scene_10",
    "locationElementId": "Element_Location_LushForest",
    "characterIds": [
      "Element_Character_Bim",
      "Element_Character_Rabbit"
    ],
    "durationSeconds": 5,
    "storyBeat": "Under a beautiful rainbow, the friends happily eat and share the bread together. Moral text appears onscreen.",
    "cinematography": {
      "scale": "wide",
      "angle": "eye-level",
      "movement": "slow camera-tilt"
    },
    "audioLayers": {
      "bgm": "Uplifting, joyful orchestral crescendo",
      "narration": "",
      "sfx": "happy puppy barks, cheerful animal laughter, wind chimes"
    },
    "startFramePrompt": "A wide eye-level shot of a sun-drenched forest clearing. Bim, now clean, dry, and fluffy, sits happily beside the white rabbit in the green vest. They are laughing and eating pieces of the golden bread together, surrounded by vibrant forest vegetation. High in the bright blue sky above the trees, a beautiful, vibrant rainbow arches perfectly across the frame. Warm, saturated golden light fills the entire scene.",
    "videoPrompt": "The camera slowly tilts upward from the laughing friends toward the bright sky. As the camera tilts up to frame the colorful rainbow, the elegant white text 'Biết sẻ chia sẽ nhận lại yêu thương.' softly fades in across the center of the screen. SFX: <joyful laughter, happy puppy barks, wind chimes chiming softly>.",
    "dialogue": "",
    "isGeneratingStartFrame": false,
    }
]
};
