// This file was automatically generated by AI Short Film Storyboard Suite (Client Fallback)
// Saved At: 2026-05-31T04:04:14.701Z

export const SAVED_PROJECT_DATA = {
  savedAt: "2026-05-31T04:04:14.701Z",
  currentStep: 9,
  highestStepReached: 9,
  globalBrief: {
  "title": "ROBOT NHẶT RÁC THÀNH PHỐ",
  "genre": "Drama",
  "aspectRatio": "16:9",
  "visualStyle": "3D Pixar",
  "language": "English",
  "scriptText": "Nội dung\nMột robot nhỏ tên R-01 được tạo ra để dọn rác. Nhưng lũ trẻ trong thành phố cứ xả rác khắp nơi khiến robot làm việc không xuể.\nCao trào\nCon sông trong thành phố bị nghẹt rác và ngập nước lớn.\nKết thúc\nBọn trẻ cùng robot dọn sạch thành phố và lập đội “Siêu Anh Hùng Môi Trường”.\nThông điệp\n“Hãy bảo vệ môi trường từ những việc nhỏ nhất.”\nLời thoại\nRobot: “Rác đang vượt quá mức cho phép.”\nBé Tôm: “Chỉ một cái túi thôi mà!”\nRobot: “Một cái túi của rất nhiều người sẽ thành cả ngọn núi.”"
},
  scenes: [
  {
    "sequenceOrder": 1,
    "description": "Nội dung",
    "durationSeconds": 4,
    "transitionLogic": "Bắt đầu cảnh quay",
    "id": "Scene_1"
  },
  {
    "sequenceOrder": 2,
    "description": "Một robot nhỏ tên R-01 được tạo ra để dọn rác.",
    "durationSeconds": 5,
    "transitionLogic": "Chuyển cảnh mờ dần (Cross-Dissolve)",
    "id": "Scene_2"
  },
  {
    "sequenceOrder": 3,
    "description": "Nhưng lũ trẻ trong thành phố cứ xả rác khắp nơi khiến robot làm việc không xuể.",
    "durationSeconds": 4,
    "transitionLogic": "Cắt máy nhanh (Cut to)",
    "id": "Scene_3"
  },
  {
    "sequenceOrder": 4,
    "description": "Cao trào",
    "durationSeconds": 5,
    "transitionLogic": "Chuyển cảnh mờ dần (Cross-Dissolve)",
    "id": "Scene_4"
  },
  {
    "sequenceOrder": 5,
    "description": "Con sông trong thành phố bị nghẹt rác và ngập nước lớn.",
    "durationSeconds": 4,
    "transitionLogic": "Cắt máy nhanh (Cut to)",
    "id": "Scene_5"
  },
  {
    "sequenceOrder": 6,
    "description": "Kết thúc",
    "durationSeconds": 5,
    "transitionLogic": "Chuyển cảnh mờ dần (Cross-Dissolve)",
    "id": "Scene_6"
  },
  {
    "sequenceOrder": 7,
    "description": "Bọn trẻ cùng robot dọn sạch thành phố và lập đội “Siêu Anh Hùng Môi Trường”.",
    "durationSeconds": 4,
    "transitionLogic": "Cắt máy nhanh (Cut to)",
    "id": "Scene_7"
  },
  {
    "sequenceOrder": 8,
    "description": "Thông điệp",
    "durationSeconds": 4,
    "transitionLogic": "Chuyển cảnh mờ dần (Cross-Dissolve)",
    "id": "Scene_8"
  }
],
  keyElements: [
  {
    "id": "Element_Character_R01",
    "type": "character",
    "name": "Robot R-01",
    "description": "A small, cute, and diligent trash-collecting robot built to clean the city, featuring highly expressive mechanical eyes and a compact body.",
    "appearanceDetails": "A small, boxy metallic robot with a rounded square head, large glowing circular blue optical eyes, and sturdy black rubber tank treads. Painted bright yellow with various levels of cleanliness depending on the scene. Features two flexible mechanical arms with three-pronged claws.",
    "imagePrompt": "Prompt of Look A: character-sheet layout: left: head-and-shoulders portrait of the character with a small, rounded rectangular robot head, large glowing circular blue optical lenses for eyes, and a shiny, polished yellow metallic chassis | right: full-body standing pose (front view, back view, and side view) with a compact boxy body, sturdy rubber tank treads, and two small mechanical arms with three-pronged claws, clean and brand new under warm workshop light, 3D Pixar style. Prompt of Look B: character-sheet layout: left: head-and-shoulders portrait of the character with the same round rectangular head but with smudged glass lenses, rusty yellow metal panels | right: full-body standing pose (front view, back view, and side view) showing mud splatters on the tank treads, scratched paint, and a slightly dented chest plate, set against a cluttered city alley, 3D Pixar style. Prompt of Look C: character-sheet layout: left: head-and-shoulders portrait of the character with polished yellow metal plates and bright blue glowing eyes | right: full-body standing pose (front view, back view, and side view) wearing a small green handmade fabric cape with a white recycling logo printed on it, standing proudly on a clean sidewalk, 3D Pixar style.",
    "looks": [
      "Look A: Clean & New - Freshly created, glossy yellow paint, clean glass eyes.",
      "Look B: Overworked & Dirty - Smudged with soot, mud splatters, slightly dented plates from working tirelessly.",
      "Look C: Eco-Hero Leader - Adorned with a small green recycling-logo cape and a clean, polished chassis."
    ],
    "imageRef": "character_robot_r-01_ref.png"
  },
  {
    "id": "Element_Character_Bao",
    "type": "character",
    "name": "Bao the City Kid",
    "description": "An energetic neighborhood kid who initially litters carelessly but undergoes a change of heart to lead the environmental cleanup crew.",
    "appearanceDetails": "An 8-year-old boy with a cute Pixar-style face, messy black hair, tanned skin, sparkling mischievous dark brown eyes, wearing a casual t-shirt, shorts, and sneakers.",
    "imagePrompt": "Prompt of Look A: character-sheet layout: left: head-and-shoulders portrait of the character with messy black hair, dark brown mischievous eyes, a warm skin tone, and a backward red baseball cap | right: full-body standing pose (front view, back view, and side view) wearing a loose red graphic t-shirt, blue denim shorts, and red sneakers, holding a crumpled plastic snack bag, standing on a colorful 3D Pixar-style city street corner. Prompt of Look B: character-sheet layout: left: head-and-shoulders portrait of the character with determined, happy eyes, wearing a handmade green cardboard eye-mask | right: full-body standing pose (front view, back view, and side view) wearing a bright green t-shirt with a custom-pinned cardboard recycling badge, a flowing green fabric cape, and clean sneakers, posing heroically, 3D Pixar style.",
    "looks": [
      "Look A: Casual Litterer - Red t-shirt with a cartoon logo, denim shorts, sneakers, backward baseball cap.",
      "Look B: Eco-Hero Uniform - Green handmade superhero cape, custom cardboard recycling badge pinned to a clean green t-shirt, green mask."
    ],
    "imageRef": "character_bao_the_city_kid_ref.png"
  },
  {
    "id": "Element_Location_CityStreets",
    "type": "location",
    "name": "City Streets",
    "description": "A vibrant but cluttered urban neighborhood with tall colourful houses, narrow alleys, and trash piled up on sidewalks.",
    "appearanceDetails": "Tall narrow buildings in warm pastel oranges, yellows, and blues, cobblestone roads, cluttered sidewalks, trash bins, soft warm golden hour lighting, 3D Pixar style.",
    "imagePrompt": "A wide-angle shot of a vibrant, colorful city street designed in a 3D Pixar style, with tall narrow houses in pastel shades of orange and blue lining the road, cluttered sidewalks with small piles of scattered plastic bottles and trash, warm golden hour sunlight casting soft shadows across the cobblestone pavement, cheerful but chaotic atmosphere, detailed textures of brick walls and asphalt, empty of people, high-fidelity cinematic rendering.",
    "imageRef": "location_city_streets_ref.png"
  },
  {
    "id": "Element_Location_FloodedRiver",
    "type": "location",
    "name": "Flooded City River",
    "description": "A concrete-banked city canal heavily choked with plastic bottles and debris, causing muddy water to overflow during a dramatic storm.",
    "appearanceDetails": "Gray concrete embankments, rushing muddy brown water, dense clusters of floating plastic waste, dark stormy sky, cool blue-gray lighting, tense dramatic tone.",
    "imagePrompt": "A dramatic wide shot of a concrete-banked city canal overflowing with muddy brown water, choked with large floating piles of plastic waste, debris, and colorful trash bags, dark stormy gray clouds filling the sky overhead casting a cool, moody blue-gray light, splashing water textures, wet concrete walls, high-stakes dramatic atmosphere, empty of people, 3D Pixar style cinematic color grade.",
    "imageRef": "location_flooded_city_river_ref.png"
  },
  {
    "id": "Element_Prop_EcoBadge",
    "type": "prop",
    "name": "Eco-Hero Badge",
    "description": "A handmade, colorful badge crafted from recycled cardboard, depicting a green leaf and a clean gear, representing the environmental team.",
    "appearanceDetails": "Circular shape, brown recycled cardboard texture, hand-painted green leaf and silver gear, safety pin on the back, slightly worn edges.",
    "imagePrompt": "A pristine closeup reference shot of a handmade cardboard badge: the badge is circular, cut from recycled brown cardboard, featuring a hand-painted green leaf intertwined with a silver gear, isolated on a clean white drafting table, soft studio lighting highlighting the cardboard fiber textures and acrylic brush strokes, cinematic shallow depth of field, ultra-sharp detail, 3D Pixar style.",
    "imageRef": "prop_eco-hero_badge_ref.png"
  }
],
  storyboard: [
  {
    "id": "Shot_01",
    "sceneId": "Scene_1",
    "locationElementId": "Element_Location_CityStreets",
    "characterIds": [],
    "durationSeconds": 4,
    "storyBeat": "Establish the vibrant but increasingly cluttered City Streets, setting up the environmental theme.",
    "cinematography": {
      "scale": "wide",
      "angle": "eye-level",
      "movement": "slow camera-tilt"
    },
    "audioLayers": {
      "bgm": "Upbeat, whimsical orchestral Pixar-style tune",
      "narration": "Chào mừng bạn đến với thành phố tươi đẹp, nơi một người bạn nhỏ sắp sửa xuất hiện.",
      "sfx": "city birds chirping, distant wind chimes, soft wind blowing"
    },
    "startFramePrompt": "A scenic wide-angle view of a vibrant city street corner. Warm golden hour sunlight illuminates tall, narrow pastel-colored buildings in shades of orange and blue. On the cobblestone sidewalk below, small piles of discarded plastic bottles and colorful wrappers are scattered around. The background features deep cinematic depth of field with soft-focused townhouses.",
    "videoPrompt": "The camera slowly tilts downward from the colorful rooftops to focus on the cluttered street pavement. Dust motes dance in the golden light rays filtering between buildings as a small piece of trash rolls gently across the empty cobblestones. <ambient wind rustling through narrow street alleys>",
    "imageRef": "shot_Shot_01_startframe.png"
  },
  {
    "id": "Shot_02",
    "sceneId": "Scene_2",
    "locationElementId": "Element_Location_CityStreets",
    "characterIds": [
      "Element_Character_R01"
    ],
    "durationSeconds": 5,
    "storyBeat": "R-01 activates for the first time, clean and ready to work.",
    "cinematography": {
      "scale": "medium close-up",
      "angle": "low-angle",
      "movement": "slow push-in"
    },
    "audioLayers": {
      "bgm": "Gentle, curious synthesizer and woodwinds",
      "narration": "Gặp gỡ R-01, một chú robot nhỏ bé, siêng năng được chế tạo để giữ sạch thành phố.",
      "sfx": "robotic whirring, cute digital chime"
    },
    "startFramePrompt": "A medium close-up of R-01, a small, boxy yellow robot with a rounded square head and pristine, polished yellow metal plates. Its large, circular blue optical eyes glow with a bright, curious light. It stands on a clean, sunny cobblestone sidewalk, looking forward.",
    "videoPrompt": "The camera slowly pushes in on R-01's face. R-01's mechanical eyes widen, blinking with a series of blue shutter rings, and its small metallic head tilts slightly to the side with curiosity. Behind it, a gentle breeze rustles the leaves of a potted street plant. <high-pitched mechanical whirring followed by a cheerful, soft digital beep>",
    "imageRef": "shot_Shot_02_startframe.png"
  },
  {
    "id": "Shot_03",
    "sceneId": "Scene_3",
    "locationElementId": "Element_Location_CityStreets",
    "characterIds": [
      "Element_Character_R01",
      "Element_Character_Bao"
    ],
    "durationSeconds": 4,
    "storyBeat": "Bao carelessly throws a plastic bag while dirty, overworked R-01 struggles behind him.",
    "cinematography": {
      "scale": "medium-wide",
      "angle": "eye-level",
      "movement": "gentle track-left"
    },
    "audioLayers": {
      "bgm": "Playful but slightly chaotic brass music",
      "narration": "Nhưng mọi chuyện không hề dễ dàng khi mọi người, đặc biệt là lũ trẻ, vẫn vô tư xả rác.",
      "sfx": "plastic crunching, rapid mechanical whirring, exhausted beeping"
    },
    "startFramePrompt": "A medium-wide shot of the city street. On the right, Bao, an 8-year-old boy wearing a red graphic t-shirt, denim shorts, and a backward red baseball cap, stands carelessly dropping a crumpled plastic bag. On the left, R-01, now smudged with soot and dirt, struggles to pull a heavy, overloaded bin of trash.",
    "videoPrompt": "The camera tracks gently to the left. Bao turns his back and walks away, while R-01 stops, its blue eyes dimming slightly as it tilts its head down in exhaustion, its mechanical arms drooping. Behind them, more colorful wrappers blow across the dirty sidewalk. <sharp rustle of a plastic bag hitting cement, followed by a low, tired mechanical sigh>",
    "imageRef": "shot_Shot_03_startframe.png"
  },
  {
    "id": "Shot_04",
    "sceneId": "Scene_4",
    "locationElementId": "Element_Location_FloodedRiver",
    "characterIds": [
      "Element_Character_R01"
    ],
    "durationSeconds": 5,
    "storyBeat": "Climax setup as a heavy storm approaches and the river begins to overflow.",
    "cinematography": {
      "scale": "wide",
      "angle": "high-angle",
      "movement": "sliding hand-drift"
    },
    "audioLayers": {
      "bgm": "Tense, low string ostinato",
      "narration": "Cơn mưa lớn ập đến, và hiểm họa bắt đầu xuất hiện.",
      "sfx": "distant thunder rumble, wind blowing, heavy rain pattering"
    },
    "startFramePrompt": "A wide shot of the concrete-banked city canal under a dark, stormy sky. R-01, covered in mud splatters and rust, stands at the edge of the gray concrete embankment, staring down at the rushing, turbulent water below. Cool blue-gray light casts a dramatic shadow.",
    "videoPrompt": "The camera slowly drifts laterally to the right. R-01's optical eyes flicker rapidly in panic as it gestures with its three-pronged metal claws toward the river. Raindrops begin to splash heavily onto its metallic head and the concrete ground. <rumble of distant thunder, followed by a heavy splash of water against the canal walls>",
    "imageRef": "shot_Shot_04_startframe.png"
  },
  {
    "id": "Shot_05",
    "sceneId": "Scene_5",
    "locationElementId": "Element_Location_FloodedRiver",
    "characterIds": [
      "Element_Character_Bao"
    ],
    "durationSeconds": 4,
    "storyBeat": "Bao stands shocked at the flooded canal, realizing the danger of the trash blockade.",
    "cinematography": {
      "scale": "medium",
      "angle": "tilted Dutch-angle",
      "movement": "slow camera-tilt"
    },
    "audioLayers": {
      "bgm": "Dramatic and urgent orchestral arrangement",
      "narration": "Dòng sông bị nghẹt cứng rác thải, đe dọa nhấn chìm cả thành phố trong lũ.",
      "sfx": "rushing muddy water, splashing waves, wind howling"
    },
    "startFramePrompt": "A tilted Dutch-angle medium shot of Bao, his red t-shirt damp from the rain, standing near the canal edge. His dark brown eyes are wide with shock as he looks down at the overflowing river filled with clogged plastic waste. The dark stormy sky forms a dramatic background.",
    "videoPrompt": "The camera tilts slowly upward to emphasize Bao's changing expression from shock to deep remorse. Bao clutches his hands together tightly, stepping back as a wave of muddy water splashes against the concrete barrier behind him. <loud rushing water noise, heavy rain pattering on clothing>",
    "imageRef": "shot_Shot_05_startframe.png"
  },
  {
    "id": "Shot_06",
    "sceneId": "Scene_6",
    "locationElementId": "Element_Location_CityStreets",
    "characterIds": [
      "Element_Character_R01",
      "Element_Character_Bao"
    ],
    "durationSeconds": 5,
    "storyBeat": "Bao apologizes to R-01 and presents the handmade Eco-Hero badge to start the team.",
    "cinematography": {
      "scale": "medium close-up",
      "angle": "eye-level",
      "movement": "slow push-in"
    },
    "audioLayers": {
      "bgm": "Uplifting, emotional solo French horn transitioning to positive strings",
      "narration": "Nhận ra sai lầm, bọn trẻ quyết định hành động cùng R-01.",
      "sfx": "clinking metal, soft rain subsiding, paper rustling"
    },
    "startFramePrompt": "A medium close-up of R-01 and Bao standing face-to-face on the damp city street. Bao, now wearing a bright green t-shirt, is holding a circular handmade cardboard Eco-Hero Badge with a painted green leaf. R-01's dirty face is tilted upward toward Bao, its blue eyes glowing softly.",
    "videoPrompt": "The camera slowly pushes in as Bao carefully pins the green cardboard recycling badge onto R-01's yellow chest plate. R-01's optical eyes instantly brighten to a brilliant cyan blue, and its small mechanical arms raise up in excitement. <soft paper rustle of the cardboard badge, followed by a sharp, happy robotic chime>",
    "imageRef": "shot_Shot_06_startframe.png"
  },
  {
    "id": "Shot_07",
    "sceneId": "Scene_7",
    "locationElementId": "Element_Location_CityStreets",
    "characterIds": [
      "Element_Character_R01",
      "Element_Character_Bao"
    ],
    "durationSeconds": 4,
    "storyBeat": "Bao and R-01 clean the streets together, wearing matching hero capes.",
    "cinematography": {
      "scale": "medium-wide",
      "angle": "low-angle",
      "movement": "gentle track-left"
    },
    "audioLayers": {
      "bgm": "Triumphant and energetic Pixar-style march",
      "narration": "Họ cùng nhau dọn sạch rác, thành lập đội Siêu Anh Hùng Môi Trường đầu tiên!",
      "sfx": "kids cheering, broom sweeping sounds, whirring tank treads"
    },
    "startFramePrompt": "A low-angle medium-wide shot of the city street under a clearing blue sky. Bao, wearing a green cardboard eye-mask and a flowing green cape, holds a broom. Beside him, R-01, wearing a matching green fabric cape over its polished yellow body, is busy collecting trash.",
    "videoPrompt": "The camera tracks to the left as Bao sweeps debris into R-01's open collection bin. R-01 moves its tank treads forward with energetic speed, vacuuming up loose papers, while other children in the background cheer and wave their hands. {Let's clean up our home!} <energetic kids cheering, broom sweeping sounds, whirring tank treads>",
    "imageRef": "shot_Shot_07_startframe.png"
  },
  {
    "id": "Shot_08",
    "sceneId": "Scene_8",
    "locationElementId": "Element_Location_CityStreets",
    "characterIds": [
      "Element_Character_R01"
    ],
    "durationSeconds": 4,
    "storyBeat": "Final triumph and message of environmental protection.",
    "cinematography": {
      "scale": "medium",
      "angle": "eye-level",
      "movement": "static block"
    },
    "audioLayers": {
      "bgm": "Warm, heartwarming orchestral resolution",
      "narration": "Bởi vì bảo vệ Trái Đất bắt đầu từ những hành động nhỏ nhất của chính chúng ta.",
      "sfx": "happy robotic beeps, soft warm breeze"
    },
    "startFramePrompt": "A medium shot of R-01 standing proudly on a sparkling clean, sunlit city street. The robot wears its green recycling-logo cape over a shiny, clean yellow chassis. The background features colorful, beautifully lit Pixar-style houses under a bright blue sky.",
    "videoPrompt": "The camera remains completely static. R-01 raises its right mechanical claw to wave happily directly at the camera, its glowing blue eyes blinking in a cheerful double-wink. {Bảo vệ Trái Đất bắt đầu từ chúng ta!} <happy high-pitched robotic beeps, soft wind rustling clean leaves>",
    "imageRef": "shot_Shot_08_startframe.png"
  }
]
};
